
Keep_Items:
  - WOODEN_PICKAXE
  - STONE_PICKAXE
  - IRON_PICKAXE
  - GOLDEN_PICKAXE
  - DIAMOND_PICKAXE
  - NETHERITE_PICKAXE
  - WOODEN_AXE
  - STONE_AXE
  - IRON_AXE
  - GOLDEN_AXE
  - DIAMOND_AXE
  - NETHERITE_AXE
  - WOODEN_SHOVEL
  - STONE_SHOVEL
  - IRON_SHOVEL
  - GOLDEN_SHOVEL
  - DIAMOND_SHOVEL
  - NETHERITE_SHOVEL
  - WOODEN_HOE
  - STONE_HOE
  - IRON_HOE
  - GOLDEN_HOE
  - DIAMOND_HOE
  - NETHERITE_HOE
